### ISSUE TITLE
How to show dropdown menu options for Icons in AppTopBar?

### ISSUE THREAD

**Issue by sivaprasad-ee** [primefaces/sakai-react#11]
In the AppTopBar there are Events, Settings, User icons. I would like to show a dropdown menu when clicked on User or Settings icon? 

Is there a way to do it using existing primereact sigma css without using external css libraries like bootstrap?

**Comment by habubey** [comment]
Could you please upgrade your version and try it one more time and let us know if the problem still continues? For now, I'm closing this.
