### ISSUE TITLE
nextjs 13

### ISSUE THREAD

**Issue by parweb** [primefaces/sakai-react#34]
any plan to upgrade nextjs to version 13 ?

**Comment by abunaum** [comment]
https://github.com/primefaces/sakai-react/pull/35

**Comment by abunaum** [comment]
> any plan to upgrade nextjs to version 13 ?

please look at the pull request, I've already pulled the request for changes in dependencies including next13 https://github.com/primefaces/sakai-react/pull/35

**Comment by kamitori** [comment]
Has anyone fixed it for nextjs 13?

**Comment by habubey** [comment]
It is now available in Nextjs 13 as you can see. If you have any issues with Next 13 and Sakai template please open a new ticket. For now, I'm closing this."
