### ISSUE TITLE
Build folder not generating

### ISSUE THREAD

**Issue by mic2112** [primefaces/sakai-react#36]
I'm running `npm run build` in the root folder of the react app, however no build folder is generated.

The screenshot shows the output of when I run the build command
<img width="590" alt="Screenshot 2022-11-09 at 10 08 18 PM" src="https://user-images.githubusercontent.com/78346435/200895112-620034ac-7c52-4eae-ae3b-2e1fcd8ee1ca.png">

Package.json
<img width="507" alt="Screenshot 2022-11-09 at 10 09 06 PM" src="https://user-images.githubusercontent.com/78346435/200895279-8d1c9413-7c13-4362-a2f4-06aac3c7e556.png">

**Comment by tuanictu97** [comment]
if you run next build Next.js will use build instead of the default .next folder.
If you want generate other folder, edit file ```next.config.js``` and add config
```
const nextConfig = {
    distDir: 'build',
    ....
};
```
[see more](https://nextjs.org/docs/api-reference/next.config.js/setting-a-custom-build-directory)
