### ISSUE TITLE
Crud search is not working

### ISSUE THREAD

**Issue by itz-nishant** [primefaces/sakai-react#78]
<img width="935" alt="Screenshot 2024-01-08 003045" src="https://github.com/primefaces/sakai-react/assets/53931540/0e80fcd9-5d19-402e-8fd0-2f1544ccae9d">
<img width="795" alt="Screenshot (6)" src="https://github.com/primefaces/sakai-react/assets/53931540/e2451d9d-d933-4802-a0c5-a34e3f037c1e">
Please fix the crud table search 
Unhandled Runtime Error
TypeError: Cannot convert undefined or null to object

**Comment by marioschvening** [comment]
has been fixed this? thanks

**Comment by krusli** [comment]
Downgrading primereact back to v9.6.2 fixes the issue - tested with a new project in the following commit: 

https://github.com/primefaces/sakai-react/commit/24dfa7906caec1ca4003627031eb172901ab29d7
